apiVersion: v1
kind: Service
metadata:
  name: {{ include "round-robin.fullname" . }}-app
  labels:
    {{- include "round-robin.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  selector:
    {{- include "round-robin.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http

