apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "round-robin.fullname" . }}-config
  labels:
    {{- include "round-robin.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.global.appEnv | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
  APP_HTTP_ADDR: ":8080"
  WORKER_HTTP_ADDR: ":8081"
  POSTGRES_USER: {{ .Values.global.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.global.postgres.database | quote }}
  POSTGRES_HOST: {{ include "round-robin.fullname" . }}-postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST: {{ include "round-robin.fullname" . }}-redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  JOB_QUEUE_NAME: {{ .Values.global.jobQueueName | quote }}

