apiVersion: v1
kind: Service
metadata:
  name: {{ include "round-robin.fullname" . }}-redis
  labels:
    {{- include "round-robin.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "round-robin.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis

