apiVersion: v1
kind: Secret
metadata:
  name: {{ include "round-robin.fullname" . }}-secrets
  labels:
    {{- include "round-robin.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | quote }}
  REDIS_PASSWORD: {{ .Values.global.redis.password | quote }}

