apiVersion: v1
kind: Service
metadata:
  name: {{ include "round-robin.fullname" . }}-worker
  labels:
    {{- include "round-robin.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  selector:
    {{- include "round-robin.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  ports:
    - name: http
      port: {{ .Values.worker.service.port }}
      targetPort: http

